### ISSUE TITLE
Command: group list fails with authentication required

### ISSUE THREAD

**Issue by akinorioyama** [gov4git/desktop-application#129]
Upon updating the Windows app, "Communities" section has only two buttons "Join a Community" and "Deploy a New Cmmunity." Upon start of the app, "No selected community. Please select or join a community" will appear. When I press "Join a Community" and enter Community URL as "https://github.com/pluralitybook/plurality,"  I received the following error.

pluralitybook/plurality--gov.public doesn't seem to have my id as far as I searched for the text of my user, akinorioyama.

![image](https://github.com/gov4git/desktop-application/assets/12178305/7b905918-233f-47c7-9b80-04b129be0a5c)

I am afraid that the log may carry some private, confidential information and haven't shared the file itself. Please inform me, otherwise.

ERROR - 2024-03-07T23:33:01.894Z: Exception running Gov4Git
ERROR - 2024-03-07T23:33:01.894Z: Command: group list --name everybody --config C:\Users\akino\.gov4git\8ea6982c37c79c338efe64eebe9bbfdcddc6dd58911d58be65ba046853ca23e5.json -v
ERROR - 2024-03-07T23:33:01.894Z: stdout: {
   "status": "error",
   "msg": "url=\"https://github.com/pluralitybook/plurality-gov.public.git\" refspecs=[\"refs/heads/main:refs/heads/main\"] err=authentication required",
   "error": {
      "msg": "url=\"https://github.com/pluralitybook/plurality-gov.public.git\" refspecs=[\"refs/heads/main:refs/heads/main\"] err=authentication required"
   }
}
ERROR - 2024-03-07T23:33:01.894Z: stderr: 2024-03-08T08:33:01+09:00 
INF /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:73 gov4git version: dev-rev-0a0f2c6-2024-03-01, os: windows, arch: amd64
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/gov4git/lib4git/must.mkErr(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:37
github.com/gov4git/lib4git/must.Panic(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:43
github.com/gov4git/lib4git/must.Errorf({0x148dd30?, 0xc000176f00}, {0x137badd?, 0xc00007d658?}, {0xc00007d628?, 0xc00007d6b8?, 0xc00007d680?})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:47 +0x65
github.com/gov4git/lib4git/must.Assertf(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:61
github.com/gov4git/lib4git/git.PullOnce({0x148dd30, 0xc000176f00}, 0xc0000a6b40, {0xc0000ac080, 0x39}, {0xc00008e4f0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/sync.go:137 +0x405
github.com/gov4git/lib4git/git.(*clonedNoCache).Pull(0xc0000a6b70?, {0x148dd30?, 0xc000176f00?})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:56 +0x15d
github.com/gov4git/lib4git/git.NoCache.clone({{0x0?, 0x124da20?}}, {0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0xc000176ea0?}, {0xc0000866a0?, 0x1a49300?}}, 0x0)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:40 +0x205
github.com/gov4git/lib4git/git.NoCache.CloneOne(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:23
github.com/gov4git/lib4git/git.CloneOne({0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0x0?}})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/clone.go:32 +0xb9
github.com/gov4git/gov4git/v2/proto/id.Clone(...)
	/home/runner/work/gov4git/gov4git/proto/id/id.go:54
github.com/gov4git/gov4git/v2/proto/gov.Clone(...)
	/home/runner/work/gov4git/gov4git/proto/gov/gov.go:19
github.com/gov4git/gov4git/v2/proto/member.ListGroupUsers({0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0xc00007da90?}}, {0xc00000a100, 0x9})
	/home/runner/work/gov4git/gov4git/proto/member/member.go:102 +0x65
github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38.1()
	/home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:61 +0x50
github.com/gov4git/lib4git/must.Try1Thru[...](0x0?)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:116 +0x6e
github.com/gov4git/gov4git/v2/gov4git/api.Invoke1[...](0x0?)
	/home/runner/work/gov4git/gov4git/gov4git/api/result.go:95 +0x1ab
github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38(0xc000159d00?, {0x136bf53?, 0x4?, 0x136be53?})
	/home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:58 +0x25
github.com/spf13/cobra.(*Command).execute(0x19e9ea0, {0xc0000b8050, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x19e4580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/gov4git/gov4git/v2/gov4git/cmd.Execute()
	/home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:113 +0x1a
main.main.func1()
	/home/runner/work/gov4git/gov4git/gov4git/main.go:15 +0xf
github.com/gov4git/lib4git/must.TryWithStack(0x0?)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:97 +0x79
main.main()
	/home/runner/work/gov4git/gov4git/gov4git/main.go:14 +0x1e

ERROR - 2024-03-07T23:33:01.894Z: Failed to run service: {
  "service": "community",
  "method": "getCommunities",
  "args": []
}
ERROR - 2024-03-07T23:33:01.894Z: Error: Command failed: C:\Users\akino\AppData\Local\Programs\gov4git-desktop-app\resources\app.asar.unpacked\node_modules\@gov4git\js-client\bin\gov4git.exe group list --name everybody --config C:\Users\akino\.gov4git\8ea6982c37c79c338efe64eebe9bbfdcddc6dd58911d58be65ba046853ca23e5.json -v
2024-03-08T08:33:01+09:00 INF /home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:73 gov4git version: dev-rev-0a0f2c6-2024-03-01, os: windows, arch: amd64
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/gov4git/lib4git/must.mkErr(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:37
github.com/gov4git/lib4git/must.Panic(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:43
github.com/gov4git/lib4git/must.Errorf({0x148dd30?, 0xc000176f00}, {0x137badd?, 0xc00007d658?}, {0xc00007d628?, 0xc00007d6b8?, 0xc00007d680?})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:47 +0x65
github.com/gov4git/lib4git/must.Assertf(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:61
github.com/gov4git/lib4git/git.PullOnce({0x148dd30, 0xc000176f00}, 0xc0000a6b40, {0xc0000ac080, 0x39}, {0xc00008e4f0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/sync.go:137 +0x405
github.com/gov4git/lib4git/git.(*clonedNoCache).Pull(0xc0000a6b70?, {0x148dd30?, 0xc000176f00?})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:56 +0x15d
github.com/gov4git/lib4git/git.NoCache.clone({{0x0?, 0x124da20?}}, {0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0xc000176ea0?}, {0xc0000866a0?, 0x1a49300?}}, 0x0)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:40 +0x205
github.com/gov4git/lib4git/git.NoCache.CloneOne(...)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/nocache.go:23
github.com/gov4git/lib4git/git.CloneOne({0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0x0?}})
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/git/clone.go:32 +0xb9
github.com/gov4git/gov4git/v2/proto/id.Clone(...)
	/home/runner/work/gov4git/gov4git/proto/id/id.go:54
github.com/gov4git/gov4git/v2/proto/gov.Clone(...)
	/home/runner/work/gov4git/gov4git/proto/gov/gov.go:19
github.com/gov4git/gov4git/v2/proto/member.ListGroupUsers({0x148dd30, 0xc000176f00}, {{0xc0000ac080?, 0x0?}, {0xc0000866a0?, 0xc00007da90?}}, {0xc00000a100, 0x9})
	/home/runner/work/gov4git/gov4git/proto/member/member.go:102 +0x65
github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38.1()
	/home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:61 +0x50
github.com/gov4git/lib4git/must.Try1Thru[...](0x0?)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:116 +0x6e
github.com/gov4git/gov4git/v2/gov4git/api.Invoke1[...](0x0?)
	/home/runner/work/gov4git/gov4git/gov4git/api/result.go:95 +0x1ab
github.com/gov4git/gov4git/v2/gov4git/cmd.glob..func38(0xc000159d00?, {0x136bf53?, 0x4?, 0x136be53?})
	/home/runner/work/gov4git/gov4git/gov4git/cmd/group.go:58 +0x25
github.com/spf13/cobra.(*Command).execute(0x19e9ea0, {0xc0000b8050, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x19e4580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/gov4git/gov4git/v2/gov4git/cmd.Execute()
	/home/runner/work/gov4git/gov4git/gov4git/cmd/root.go:113 +0x1a
main.main.func1()
	/home/runner/work/gov4git/gov4git/gov4git/main.go:15 +0xf
github.com/gov4git/lib4git/must.TryWithStack(0x0?)
	/home/runner/go/pkg/mod/github.com/gov4git/lib4git@v0.0.33/must/must.go:97 +0x79
main.main()
	/home/runner/work/gov4git/gov4git/gov4git/main.go:14 +0x1e

INFO - 2024-03-07T23:33:02.104Z: GitHub Request: {
  "status": 200,
  "url": "https://api.github.com/user",
  "headers": {

**Comment by akinorioyama** [comment]
As guided by @petar , the persistent behavior was removed after the user deleted a temporarily saved data, which is proprietary for v1, under the folders such as ~/.gov4git directory on **Mac** computers and "C:\Users<user_id>.gov4git" on **Windows** machines. The deletion will require that the user send a request to join the community again. Upon approval of the request, the user can start prioritizing votes on Gov4Git.
![image](https://github.com/gov4git/desktop-application/assets/12178305/edb3934c-ada7-4c19-bf60-973c999d85cc)
